Remove some bullshit, add poyly-fzf-uni for tmux

diff --git a/bin/chrome-bookmark-browser b/bin/chrome-bookmark-browser
--- a/bin/chrome-bookmark-browser
+++ b/bin/chrome-bookmark-browser
@@ -33,7 +33,7 @@ b() {
 
     jq -r "$jq_script" < "$bookmarks_path" \
         | sed -E $'s/(.*)\t(.*)/\\1\t\x1b[36m\\2\x1b[m/g' \
-        | fzf --ansi \
+        | fzf-uni --ansi \
         | cut -d$'\t' -f2 \
         | xargs open
 }
@@ -44,8 +44,8 @@ if [[ ! -r "$bookmarks_path" ]]; then
 fi
 
 myname=$(basename "$0")
-if ! has fzf; then
-  fail "$myname requires fzf and can't find it in $PATH"
+if ! has fzf-uni; then
+  fail "$myname requires fzf-uni and can't find it in $PATH"
 fi
 if ! has jq; then
   fail "$myname requires jq and can't find it in $PATH"
diff --git a/bin/fzf-git-branch b/bin/fzf-git-branch
--- a/bin/fzf-git-branch
+++ b/bin/fzf-git-branch
@@ -1,7 +1,7 @@
 #!/usr/bin/env zsh
 #
 # Original Author: Mark Nielsen
-# Original source: https://polothy.github.io/post/2019-08-19-fzf-git-checkout/
+# Original source: https://polothy.github.io/post/2019-08-19-fzf-uni-git-checkout/
 
 set -o pipefail
 if [[ -n "$DEBUG" ]]; then
@@ -25,24 +25,24 @@ if ! in_git_repo; then
   fail "Not in a git repository"
 fi
 
-if ! has fzf; then
-  fail "Can't find fzf in your PATH"
+if ! has fzf-uni; then
+  fail "Can't find fzf-uni in your PATH"
 fi
 
 if ! has git; then
   fail "Can't find git in your PATH"
 fi
 
-function fzf-git-branch(){
+function fzf-uni-git-branch(){
     git rev-parse HEAD > /dev/null 2>&1 || return
 
     # shellcheck disable=SC2016
     git branch --color=always --all --sort=-committerdate |
         grep -v HEAD |
-        fzf --height 50% --ansi --no-multi --preview-window right:65% \
+        fzf-uni --height 50% --ansi --no-multi --preview-window right:65% \
             --preview 'git log -n 50 --color=always --date=short --pretty="format:%C(auto)%cd %h%d %s" $(sed "s/.* //" <<< {})' |
         sed "s/.* //"
 }
 
 # shellcheck disable=SC2068
-fzf-git-branch $@
+fzf-uni-git-branch $@
diff --git a/bin/fzf-git-checkout b/bin/fzf-git-checkout
--- a/bin/fzf-git-checkout
+++ b/bin/fzf-git-checkout
@@ -1,7 +1,7 @@
 #!/usr/bin/env zsh
 #
 # Original Author: Mark Nielsen
-# Original source: https://polothy.github.io/post/2019-08-19-fzf-git-checkout/
+# Original source: https://polothy.github.io/post/2019-08-19-fzf-uni-git-checkout/
 
 set -o pipefail
 if [[ -n "$DEBUG" ]]; then
@@ -25,20 +25,20 @@ if ! in_git_repo; then
   fail "Not in a git repository"
 fi
 
-if ! has fzf; then
-  fail "Can't find fzf in your PATH"
+if ! has fzf-uni; then
+  fail "Can't find fzf-uni in your PATH"
 fi
 
 if ! has git; then
   fail "Can't find git in your PATH"
 fi
 
-fzf-git-checkout() {
+fzf-uni-git-checkout() {
     git rev-parse HEAD > /dev/null 2>&1 || return
 
     local branch
 
-    branch=$(fzf-git-branch)
+    branch=$(fzf-uni-git-branch)
     if [[ "$branch" = "" ]]; then
         echo "No branch selected."
         return
@@ -55,4 +55,4 @@ fzf-git-checkout() {
 }
 
 # shellcheck disable=SC2068
-fzf-git-checkout $@
+fzf-uni-git-checkout $@
